### ISSUE TITLE
Calibration emails can not be sent, resulting in near total failure of the fishtank monitor

### ISSUE THREAD

**Issue by edwillis** [edwillis/FishtankMonitor#29]
The failure looks like so in the logs:

2015-07-12 14:02:32,847 |    notifications |  INFO | calibration period expired - setting last calibration  to 1436724152.847447
2015-07-12 14:02:32,849 |    notifications |  INFO | calibration noifications are enabled, writing last cal to db
2015-07-12 14:02:32,902 |    notifications |  INFO | it's time to calibrate, sending email
2015-07-12 14:02:32,904 | fishtank_monitor | ERROR | encountered exception in main_loop, retrying:  UnboundLocalError("local variable 'msg' referenced before assignment",)
Traceback (most recent call last):
  File "fishtank_monitor.py", line 184, in <module>
    main_loop(notifiers)
  File "fishtank_monitor.py", line 161, in main_loop
    notifier(conn, monitor)
  File "/home/pi/FishtankMonitor/fishtank_monitor/notifications.py", line 164, in __call__
    msg = MIMEText(msg)
UnboundLocalError: local variable 'msg' referenced before assignment

No emails are sent once this problem is seen and no measurements are written to the database.

**Comment by edwillis** [comment]
402f909
